[[KNITRO]]
git-tree-sha1 = "a9b7b5d6018fe63d10edba9341596eaa80010aad"
arch = "x86_64"
os = "linux"

    [[KNITRO.download]]
    sha256 = "d6d533cb0e0adcf4503ed0d85485ca6bb65dd83d71fc99927e18a59d83465393"
    url = "https://github.com/jump-dev/KNITRO_jll.jl/releases/download/v15.0.1-binary/x86_64-linux-gnu.tar.bz2"
[[KNITRO]]
git-tree-sha1 = "eb96189d188a0af9ab16d1962584c3278e61a2dc"
arch = "aarch64"
os = "macos"

    [[KNITRO.download]]
    sha256 = "01d5c031b93c78abc2b603f34bbe038bd729a719dbb28683211613a7871b76c4"
    url = "https://github.com/jump-dev/KNITRO_jll.jl/releases/download/v15.0.1-binary/aarch64-apple-darwin.tar.bz2"
[[KNITRO]]
git-tree-sha1 = "c1d140c66fa381df2790a384912bd1f868f470b2"
arch = "x86_64"
os = "windows"

    [[KNITRO.download]]
    sha256 = "9c59ed932d8200d9929bf182652473f6f8f2fe82d8d1dc71e352a4e979b76138"
    url = "https://github.com/jump-dev/KNITRO_jll.jl/releases/download/v15.0.1-binary/x86_64-w64-mingw32.tar.bz2"
